import type { AppSettings } from './types'

export const DEFAULT_SETTINGS: AppSettings = {
  fftSize: 1024,
  smoothingTimeConstant: 0.75,
  lowThresholdMultiplier: 1.45,
  lowMidThresholdMultiplier: 1.6,
  midThresholdMultiplier: 1.7,
  highThresholdMultiplier: 1.8,
  flashDurationMs: 80,
  decayMs: 220,
  cooldownMs: 130,
  sensitivity: 1,
  maxFlashesPerSecond: 5,
  idleColor: '#050005',
  basePinkColor: '#ff4fd8',
  hotPinkColor: '#ff8bea',
  whiteFlashColor: '#ffffff',
  softMode: false,
  selectedDisplayId: null,
  selectedAudioInputId: null,
  useMorphing: false,
  morphingAlgorithm: 'liquid',
  morphingPresetId: 'ritual-drift',
  debugMorphingVisibility: false,
  morphingOpacity: 0.45,
  morphingMinOpacity: 0.30,
  morphingLuminanceBoost: 0.35,
  morphingGlowIntensity: 0.55,
  morphingContrast: 1.25,
  morphingScale: 1.15,
  morphingEdgeSoftness: 0.65,
  backgroundDarkness: 0.92,
  flashTriggerBandMin: 2200,
  flashTriggerBandMax: 5200,
  secondaryFlashBandMin: 0,
  secondaryFlashBandMax: 0,
  flashThreshold: 4.20,
  transientDelta: 0.34,
  lowDominanceBlockRatio: 1.35,
  subMovement: 0.26,
  kickMovement: 0.08,
  flashOnKick: false,
}
