import type { MorphingPreset } from './types'

export const MORPHING_PRESETS: MorphingPreset[] = [
  {
    id: 'ritual-drift',
    name: 'Ritual Drift',
    shapeCount: 3,
    blur: 70,
    opacity: 0.55,
    speed: 0.12,
    deformation: 0.45,
    scale: 1.15,
    blendMode: 'screen',
    lowScaleAmount: 0.18,
    lowMidDeformationAmount: 0.22,
    midOpacityAmount: 0.18,
    highNoiseAmount: 0.06,
    flashEdgeAmount: 0.20,
  },
  {
    id: 'dream-plasma',
    name: 'Dream Plasma',
    shapeCount: 4,
    blur: 110,
    opacity: 0.32,
    speed: 0.055,
    deformation: 0.48,
    scale: 1.50,
    blendMode: 'screen',
    lowScaleAmount: 0.05,
    lowMidDeformationAmount: 0.14,
    midOpacityAmount: 0.22,
    highNoiseAmount: 0.025,
    flashEdgeAmount: 0.035
  },
  {
    id: 'submerged-organism',
    name: 'Submerged Organism',
    shapeCount: 3,
    blur: 95,
    opacity: 0.36,
    speed: 0.045,
    deformation: 0.62,
    scale: 1.35,
    blendMode: 'lighten',
    lowScaleAmount: 0.04,
    lowMidDeformationAmount: 0.24,
    midOpacityAmount: 0.12,
    highNoiseAmount: 0.015,
    flashEdgeAmount: 0.025
  },
  {
    id: 'industrial-ectoplasm',
    name: 'Industrial Ectoplasm',
    shapeCount: 2,
    blur: 80,
    opacity: 0.42,
    speed: 0.065,
    deformation: 0.72,
    scale: 1.42,
    blendMode: 'screen',
    lowScaleAmount: 0.06,
    lowMidDeformationAmount: 0.32,
    midOpacityAmount: 0.10,
    highNoiseAmount: 0.035,
    flashEdgeAmount: 0.04
  },
  {
    id: 'slow-lysergic-field',
    name: 'Slow Lysergic Field',
    shapeCount: 5,
    blur: 130,
    opacity: 0.24,
    speed: 0.035,
    deformation: 0.36,
    scale: 1.75,
    blendMode: 'screen',
    lowScaleAmount: 0.025,
    lowMidDeformationAmount: 0.08,
    midOpacityAmount: 0.24,
    highNoiseAmount: 0.01,
    flashEdgeAmount: 0.015
  },
  {
    id: 'blacklight-pollen',
    name: 'Blacklight Pollen',
    shapeCount: 7,
    blur: 65,
    opacity: 0.26,
    speed: 0.075,
    deformation: 0.28,
    scale: 1.10,
    blendMode: 'screen',
    lowScaleAmount: 0.03,
    lowMidDeformationAmount: 0.10,
    midOpacityAmount: 0.18,
    highNoiseAmount: 0.07,
    flashEdgeAmount: 0.025
  },
  {
    id: 'molten-memory',
    name: 'Molten Memory',
    shapeCount: 3,
    blur: 100,
    opacity: 0.34,
    speed: 0.052,
    deformation: 0.55,
    scale: 1.48,
    blendMode: 'lighten',
    lowScaleAmount: 0.05,
    lowMidDeformationAmount: 0.20,
    midOpacityAmount: 0.16,
    highNoiseAmount: 0.02,
    flashEdgeAmount: 0.03
  },
  {
    id: 'ritual-afterimage',
    name: 'Ritual Afterimage',
    shapeCount: 2,
    blur: 145,
    opacity: 0.30,
    speed: 0.028,
    deformation: 0.26,
    scale: 1.90,
    blendMode: 'screen',
    lowScaleAmount: 0.02,
    lowMidDeformationAmount: 0.06,
    midOpacityAmount: 0.20,
    highNoiseAmount: 0.008,
    flashEdgeAmount: 0.02
  },
  {
    id: 'spectral-membrane',
    name: 'Spectral Membrane',
    shapeCount: 4,
    blur: 75,
    opacity: 0.31,
    speed: 0.06,
    deformation: 0.68,
    scale: 1.28,
    blendMode: 'screen',
    lowScaleAmount: 0.04,
    lowMidDeformationAmount: 0.18,
    midOpacityAmount: 0.14,
    highNoiseAmount: 0.05,
    flashEdgeAmount: 0.035
  },
  {
    id: 'nocturnal-bloom',
    name: 'Nocturnal Bloom',
    shapeCount: 3,
    blur: 115,
    opacity: 0.33,
    speed: 0.04,
    deformation: 0.40,
    scale: 1.60,
    blendMode: 'lighten',
    lowScaleAmount: 0.03,
    lowMidDeformationAmount: 0.12,
    midOpacityAmount: 0.26,
    highNoiseAmount: 0.018,
    flashEdgeAmount: 0.02
  },
  {
    id: 'machine-hallucination',
    name: 'Machine Hallucination',
    shapeCount: 3,
    blur: 60,
    opacity: 0.38,
    speed: 0.085,
    deformation: 0.82,
    scale: 1.25,
    blendMode: 'screen',
    lowScaleAmount: 0.04,
    lowMidDeformationAmount: 0.34,
    midOpacityAmount: 0.10,
    highNoiseAmount: 0.06,
    flashEdgeAmount: 0.035
  },
  {
    id: 'imaginary-friend',
    name: 'Amico Immaginario',
    shapeCount: 2,
    blur: 105,
    opacity: 0.34,
    speed: 0.038,
    deformation: 0.58,
    scale: 1.52,
    blendMode: 'screen',
    lowScaleAmount: 0.025,
    lowMidDeformationAmount: 0.16,
    midOpacityAmount: 0.28,
    highNoiseAmount: 0.022,
    flashEdgeAmount: 0.018
  },
  {
    id: 'alien-contact',
    name: 'Contatto Alieno',
    shapeCount: 5,
    blur: 90,
    opacity: 0.30,
    speed: 0.048,
    deformation: 0.74,
    scale: 1.44,
    blendMode: 'lighten',
    lowScaleAmount: 0.018,
    lowMidDeformationAmount: 0.12,
    midOpacityAmount: 0.18,
    highNoiseAmount: 0.085,
    flashEdgeAmount: 0.025
  }
]
