export const BRAIN_CONFIG = {
  pipelineRevision: 'organic-no-architecture-v35',
  phraseSampleCount: 3,
  phraseMemoryCount: 12,
  storyMemoryCount: 6,
  storyQueueTarget: 3,
  storyFrameMin: 4,
  storyFrameMax: 4,
  storyMaxNewTokens: 900,
  sceneMaxNewTokens: 320,
  storyMinNewTokens: 96,
  sceneMinNewTokens: 48,
  frameDurationMs: 9_000,
  transitionDurationMs: 8_000,
  interstoryMinimumDurationMs: 6_000,
  generationTimeoutMs: 180_000,
  storyModelId: 'onnx-community/Qwen3-0.6B-ONNX',
  visualModelId: 'onnx-community/Qwen3-0.6B-ONNX',
  imageModelId: 'sd-turbo' as const,
  highQualityImageModelId: 'janus-pro-1b' as const,
  imageWidth: 512,
  imageHeight: 512,
  imageGenerationTimeoutMs: 180_000,
  imageCapabilityTimeoutMs: 12_000,
  imageModelLoadTimeoutMs: 20 * 60_000,
  retryInitialDelayMs: 5_000,
  retryMaximumDelayMs: 60_000,
  vectorMaxSourceBytes: 12 * 1024 * 1024,
  modelDtype: 'q4' as const,
  webGpuModelDtype: 'q4f16' as const,
  aiEnabled: true,
  statusOpacity: 0.28,
} as const
